name: Pulumi

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
env:
  PIPENV_VENV_IN_PROJECT: 1
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv install -d
      
      - uses: pulumi/actions@v4
        name: Install Pulumi CLI only
        with:
          stack-name: dev
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PIPENV_VENV_IN_PROJECT: 1
      - name: Install dependencies
        run: pipenv run pulumi preview -s dev --logtostderr
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PIPENV_VENV_IN_PROJECT: 1

      - uses: pulumi/actions@v4
        if: false
        with:
          command: preview
          stack-name: dev
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
